name: execute terraform

on:
    push:
        branches:
            - main
    workflow_dispatch:
      inputs:
        selected_environment:
          description: 'approve'
          required: true
          default: '---'
          type: choice
          options:
            - OK
            - NG

env:
  TF_VAR_APP_NAME: ${{ secrets.APP_NAME }}
  TF_VAR_KEY_NAME: ${{ secrets.KEY_NAME }}
  TF_VAR_REGION: ${{ secrets.REGION }}

jobs:
    terraform-dry-run:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.9.5"

            - name: 
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
                aws-region: ap-northeast-1

            - name: Terraform Init
              run: terraform -chdir=./aws init

            - name: Terraform Plan
              run: terraform -chdir=./aws plan -out=tfplan
        
            - name: Save Plan Result
              uses: actions/upload-artifact@v4
              with:
                name: tfplan
                path: ./aws/tfplan

    approve:
      needs: terraform-dry-run
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      steps:
        - name: Approval Needed
          run: echo "Please approve the apply step."

    terraform-apply:
      needs: [ approve, terraform-dry-run ]
      runs-on: ubuntu-latest
      if: ${{ github.event.inputs.selected_environment == 'OK' }}
      permissions:
        id-token: write
        contents: read

      steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.9.5"

            - name: 
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
                aws-region: ap-northeast-1

            - name: Download Plan File
              uses: actions/download-artifact@v4
              with:
                name: tfplan
                path: ./aws

            - name: Check Plan File
              run: ls -la ./aws

            - name: Terraform Apply
              run: terraform -chdir=./aws apply -auto-approve ./aws/tfplan